import Config

# Track environment at runtime (for conditional behavior in workers, etc.)
config :social_objects, env: :dev

# Configure your database
# Supports DATABASE_URL environment variable or defaults to local PostgreSQL
if database_url = System.get_env("DATABASE_URL") do
  config :social_objects, SocialObjects.Repo,
    url: database_url,
    pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
    stacktrace: true,
    show_sensitive_data_on_connection_error: true
else
  config :social_objects, SocialObjects.Repo,
    username: "postgres",
    password: "postgres",
    hostname: "localhost",
    database: "social_objects_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
bridge_port = String.to_integer(System.get_env("TIKTOK_BRIDGE_PORT") || "8080")
bridge_watcher_enabled? = System.get_env("TIKTOK_BRIDGE_WATCHER", "true") != "false"

bridge_port_available? =
  case :gen_tcp.connect(~c"127.0.0.1", bridge_port, [:binary, active: false], 100) do
    {:ok, socket} ->
      :gen_tcp.close(socket)
      false

    {:error, :econnrefused} ->
      true

    {:error, _} ->
      true
  end

bridge_watcher =
  if bridge_watcher_enabled? and bridge_port_available? do
    [
      node: [
        "server.js",
        cd: Path.expand("../services/tiktok-bridge", __DIR__),
        env: %{"PORT" => Integer.to_string(bridge_port)}
      ]
    ]
  else
    []
  end

config :social_objects, SocialObjectsWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4001")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "cbp7vzcpMcH98t9a7NIO3LrSWzXeN5nccqZdEFe2QWydund6F2h5TvtuAdvhv1dz",
  watchers:
    [
      esbuild: {Esbuild, :install_and_run, [:social_objects, ~w(--sourcemap=inline --watch)]},
      tailwind: {Tailwind, :install_and_run, [:social_objects, ~w(--watch)]}
    ] ++ bridge_watcher

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :social_objects, SocialObjectsWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/social_objects_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :social_objects, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Enable Swoosh API client for SendGrid (also works with Local adapter)
config :swoosh, :api_client, Swoosh.ApiClient.Req

# Avoid storing creator avatars in development unless explicitly enabled
config :social_objects, :creator_avatars, store_in_storage: false, store_locally: true

# Shopify configuration is set in config/runtime.exs after loading .env

# Oban cron jobs are disabled in dev (base config in config.exs)
# Workers must be triggered manually via the UI
